# Generated by Django 5.2.1 on 2025-05-26 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_room_is_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='name',
            new_name='dorm_name',
        ),
        migrations.RemoveField(
            model_name='review',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='room',
            name='furniture',
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='booking',
            name='check_in',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='landlord',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landlord',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landlord',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='landlord',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='landlord',
            name='dorm_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landlord',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='cleanliness',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='review',
            name='comfort',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='room',
            name='aircon_count',
            field=models.PositiveIntegerField(default=0, verbose_name='aircon_count'),
        ),
        migrations.AddField(
            model_name='room',
            name='bed_count',
            field=models.PositiveIntegerField(default=0, verbose_name='bed_count'),
        ),
        migrations.AddField(
            model_name='room',
            name='chair_count',
            field=models.PositiveIntegerField(default=0, verbose_name='chair_count'),
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='desk_count',
            field=models.PositiveIntegerField(default=0, verbose_name='desk_count'),
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/'),
        ),
        migrations.AddField(
            model_name='room',
            name='lease_duration_months',
            field=models.PositiveIntegerField(default=1, verbose_name='Lease Duration (Months)'),
        ),
        migrations.AddField(
            model_name='room',
            name='refrigerator_count',
            field=models.PositiveIntegerField(default=0, verbose_name='refrigerator_count'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='room',
            name='sofa_count',
            field=models.PositiveIntegerField(default=0, verbose_name='sofa_count'),
        ),
        migrations.AddField(
            model_name='room',
            name='table_count',
            field=models.PositiveIntegerField(default=0, verbose_name='table_count'),
        ),
        migrations.AddField(
            model_name='room',
            name='tv_count',
            field=models.PositiveIntegerField(default=0, verbose_name='tv_count'),
        ),
        migrations.AddField(
            model_name='room',
            name='wardrobe_count',
            field=models.PositiveIntegerField(default=0, verbose_name='wardrobe_count'),
        ),
        migrations.AddField(
            model_name='room',
            name='water_heater_count',
            field=models.PositiveIntegerField(default=0, verbose_name='water_heater_count'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.room'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.tenant'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('tenant', 'Tenant'), ('landlord', 'Landlord')], default='tenant', max_length=20),
        ),
        migrations.AlterField(
            model_name='landlord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='review',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='room',
            name='landlord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='myapp.landlord'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
